### ISSUE TITLE
tests: ssh to rivanna

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#1]
we need an ssh test to rivanna prior to the tests and if not passes exclude all tests that do ssh to rivanna

**Comment by laszewsk** [comment]
if vpn is not there test shoudl fail without actually doing ssh

**Comment by jpfleischer** [comment]
this has been implemented
https://github.com/cloudmesh/cloudmesh-cc/commit/c4c98c6f005891ffa8773321e8e32fbf7defda10
