### ISSUE TITLE
install: provide documentation on how to install graphviz (the native program/dot)

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#13]
- [x] windows
- [x] mac
- [x] linux (also jackson)

**Comment by jpfleischer** [comment]
this seems to be sufficient. https://github.com/cybertraining-dsc/reu2022/blob/main/project/graphs/graphs-graphviz/graphviz.md
maybe before closing this issue, we should make a point of it to the reader to install graphviz, and direct them to this markdown file, in the main README.md of this repository.

what do you think?

**Comment by jpfleischer** [comment]
i think this is done. https://github.com/cloudmesh/cloudmesh-cc/blob/main/api/source/ultimate_documentation.md#requirements

**Comment by jpfleischer** [comment]
https://cloudmesh.github.io/cloudmesh-cc/installation.html
