### ISSUE TITLE
Clarify routes and responses following REST design principals

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#17]
- [x] service: lots of errors also in cc.py where we call it
- [ ] add_job has no return (bool)
- [x] needs complete review and partial reimplementation
- [x] graoh should refresh upon detection of SVG file change
- [x] table implementation from datatables is missing
- [x] example is not documenting all methods using REST

**Comment by jpfleischer** [comment]
not sure if add_job needs a boolean return. https://github.com/cloudmesh/cloudmesh-cc/blob/c47bd689d1e34b6636d3a5192c1349fd45e6a37a/cloudmesh/cc/service/service.py#L1429

as it is, it returns the workflow and its jobs, for user confirmation that the new job is in there. if it fails then it throws some exception.

and i dont think cc.py has any errors when it is called so maybe this is just a really old issue.

**Comment by laszewsk** [comment]
maybe we need to do 

https://restfulapi.net/http-status-codes/

**Comment by jpfleischer** [comment]
rest test is finished https://github.com/cloudmesh/cloudmesh-cc/blob/main/tests/test_012_service_localhost.py
