### ISSUE TITLE
remove: deprecated/jacksonjob

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#19]
[@Jackson Miskill](https://cloudmesh-reu2022.slack.com/team/U03EFNF4XHV)
 there is a jackson job in deprecated. can you go through it, I like to remove it ASAP
has this been reviewed?
can we remove?

**Comment by j-miskill** [comment]
Looked through the job and didn't see anything worth keeping, so I went ahead and deprecated it (I straight up deleted it)
