### ISSUE TITLE
Complete documentation of tensorflow tutorial with all sections

### ISSUE THREAD

**Issue by abeck14** [cloudmesh/cloudmesh-cc#24]
https://github.com/cybertraining-dsc/reu2022/blob/main/project/hpc/rivanna-tensorflow.md

**Comment by laszewsk** [comment]
where is url

**Comment by abeck14** [comment]
https://github.com/cybertraining-dsc/reu2022/blob/main/project/rivanna-tensorflow.md

**Comment by laszewsk** [comment]
can we please add a git repo where the examples reside and also let the people no how to use that git repo in a later section

**Comment by abeck14** [comment]
I just formatted the sbatch script example in the same way as in the Rivanna tutorial. Didn't use any real files in the example, just replaced it with mydemojob.py as I think the filenames in the example are trivial

**Comment by laszewsk** [comment]
incomplete

**Comment by laszewsk** [comment]
duplicated of #25
