### ISSUE TITLE
focus back to terminal when a graph is displayed

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#26]
I wonder if there is a way the when we do a graph update in gopen/open/web browser that this is actually done in the background, but the focus stays with the terminal. ....

- [x] explore sxiv in linux
- [x] osx: gaplin does auto read when modified 
- [ ] explore in windows
- [ ] add option autoread=True to enable it (implement) otherwise it uses update upplication

**Comment by laszewsk** [comment]
* OSX: if using gaplin there is no need to open gaplin every time, just have it auto read. Code has been modified

**Comment by j-miskill** [comment]
May have been finished, but I am not sure.

**Comment by laszewsk** [comment]
is there prg on osx and wiindows that autoloads an SVG upon change, if we can use that we have likely solved the issue as this can be done in parallel has to be checked

**Comment by laszewsk** [comment]
cli important to document.
some machines do update automatically once you first call open

**Comment by jpfleischer** [comment]
the latest change to common has semi-fixed this. in windows, the browser only raises once.. but if you focus back to terminal then the browser wont refocus on itself for the rest of the workflow

**Comment by jpfleischer** [comment]
windows now refocuses on terminal https://github.com/cloudmesh/cloudmesh-cc/commit/e6d31e8d0afd80c2a9baa721f32dc424b56cc1fa

**Comment by jpfleischer** [comment]
will not fix. gregor determined not to fix as we have a web browser interface that stays focused and we will switch to mainly using the web browser interface.
