### ISSUE TITLE
doc: cloudmesh-cc documentation

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#3]
write readme with install documentation for all osses

**Comment by j-miskill** [comment]
This morning, I finished a write up on the workflow. It definitely needs review, as I don't think I did a great job on it.

**Comment by laszewsk** [comment]
where is url?

**Comment by laszewsk** [comment]
url missing

**Comment by j-miskill** [comment]
https://github.com/cybertraining-dsc/reu2022/blob/main/project/cloudmesh-cc/workflow.md

This is all I did for the workflow.

**Comment by laszewsk** [comment]
is this and other md files in the 

reu2022.yaml

we need to add ....

**Comment by jpfleischer** [comment]
https://cloudmesh.github.io/cloudmesh-cc/installation.html
