### ISSUE TITLE
pytest for SHell commands

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#35]
please see version i just checked in, please addd unit test to
cloudmesh-common/tests/test_shell_command
for ls and any other common Shell commands that you or team members use. please do pull reuest
- [x] Shell.ls( ... )
- [x] Shell.mkdir( ... )
- [x] Shell.ps( ... )
- [x] Shell.run ( .... ) for linux, mac, windows
- [x] Shell.map_filename (i think we have a test somewhere for that )
- [x] others ???

**Comment by jpfleischer** [comment]
https://github.com/cloudmesh/cloudmesh-common/commit/6773addcf39ff3b6d7e013c6d61e55797ecd021c
