### ISSUE TITLE
configure windows machine

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#41]
Alision please develop a section windows-iconfiguration.md
in whcih you place your experience in what you needed to tour computer. at least at bullet form i remember
- [x] uninstall virtualbox if too old (its on the web site I think, ), however we could give recommendation do just install, if needed reinstall ( i do not think we need to reinstall)
- [x] document bios settings for docker ... point out may be different for each computer, locate in documents and point at least to the docker document that descries this
- [x] document the settings change internally on machine
- [x] document how to install wsl and use 22.04 ubuntu
- [x] document how to configure gitbash, e.g. use native linux line ending and stress how important that is for the code we run. There is actually another way of doing it, e.g. you have programming bugs in windows, but if you do the setting you do not :wink: easy way to fix things ...
- [x] uninstall and reinstall pycharm
- [x] (optional) do not use vs code but use pycharm so team can use consitantly inspect code, and reformat code. reinstall pycharm to the latest version
- [x] document how to switch tabs for makefiles (useful for other OSSes also)
- [x] document how to block format to 79 chars
- [x] document how to install emacs and other cooll commands
you can use chocolatey if that simplifies things
- [x] document how to uninstall conda or disable it
remember that cloudmesh does run in conda, but i did not want to get into yet another 3 weeks inactivity due to configuration issues.
if conda, would be good to create the conda yml file for each package and put in repo so we can use the conda install directly from the git repoo ... (dont do it just document how to uninstall conda)
- [x] do not spend more then 30min-1 hour on this other tasks more important

Message general

**Comment by laszewsk** [comment]
incomplete as check marks not added

**Comment by jpfleischer** [comment]
latest changes: https://github.com/cybertraining-dsc/reu2022/blob/main/project/windows-configuration.md

**Comment by laszewsk** [comment]
I made some more changes, also missing is the gitbash instalation that it needs /r comment, i think you set this in chokolatey, but do not explain ... can you take a look

**Comment by laszewsk** [comment]
can we identify a link that describes how to set virtualization in windows ... I think that is all we need, people can then look there

so we learned 
a) users must uninstall old version of pycharm
b) users must ininstall old versions of gitbash so we can reinsitall it with proper config
c) users must research how to set virtualization

Unfortunately this was not executed for 3 weeks in our REU and we were delayed, only after I installed a windows machine myself, it was identified that the guideance provided was not followed or not understood.

we need to integrate a-c somehow in the documentation

**Comment by jpfleischer** [comment]
you can find the link in this section. https://github.com/cybertraining-dsc/reu2022/blob/main/project/windows-configuration.md#docker

it is by berkeley. but i will also include your part b) since we dont really talk about uninstalling gitbash. i will fix that now

**Comment by jpfleischer** [comment]
the /r (if you were referring to line ending) has been expanded upon in https://github.com/cybertraining-dsc/reu2022/blob/main/project/windows-configuration.md#install-git-bash

**Comment by jpfleischer** [comment]
this is done. https://github.com/cybertraining-dsc/reu2022/blob/main/project/windows-configuration.md#docker
waiting for review.
