### ISSUE TITLE
Bug: ipynb in clean example does ot report progress on linux

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#42]
example hangs as the progress on linux for th d.ipynb in clean is not reporting progress.

The intermitted solution is to not include ipynb initially in the clean example or to fix this issue

**Comment by jpfleischer** [comment]
thanks for your report, i think i know what the fix is. can you first stand in cloudmesh-cc and then run `pip install -e .` ? my suspicion is that papermill or cloudmesh-progress is not installed. and make sure cloudmesh-cc, and cloudmesh-common is up-to-date with git pull

**Comment by jpfleischer** [comment]
with the help of a linux virtual machine, i discovered that the issue was missing requirements, ipython and ipykernel.
fixed https://github.com/cloudmesh/cloudmesh-cc/commit/d637990caa5a6d5393abb19fe5bbf035db4e2ebf
