### ISSUE TITLE
cms cc stop

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#47]
cms cc start starts the workfow from commandline

we need cms cc stop that kills the workflow server.

this is useful when a process runs away during development

**Comment by laszewsk** [comment]
current cms cc stop is not working

**Comment by jpfleischer** [comment]
it now works for mac and linux. https://github.com/cloudmesh/cloudmesh-cc/commit/3e987dcd63b1a11c02bdf2d6fdfdc85cf693a6ce

...but is difficult for windows. how unfortunate!

**Comment by jpfleischer** [comment]
it was crazy and exhausting to implement windows but i did it
https://github.com/cloudmesh/cloudmesh-cc/commit/72aede499961b7042814ea5bc077df354a7875ae
