### ISSUE TITLE
man page to gui

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#48]
add Documentation-> Man page that liststhe content of the manual page of cc in markdown or simple ascii text 

cms cc hle or cms help cc can do this, we also have cms man cc, but I am not sure if last one works.

Reason we want tis is to also allow users to know about cmmandline feature

**Comment by jpfleischer** [comment]
https://cloudmesh.github.io/cloudmesh-cc/manual/cc.html

could this be completed?

**Comment by jpfleischer** [comment]
added

http://127.0.0.1:8000/manpage

**Comment by laszewsk** [comment]
approved
