### ISSUE TITLE
test python 3.10.7 install

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#49]
- [x] Windows
- [x] Linux
- [x] macOS intel
- [x] macOS M1

**Comment by laszewsk** [comment]
```
python3 -m venv ~/ENV3
python --version
pip install pip -U
pip install cloudmesh-installer
ssh-add
cloudmesh-installer --ssh get cc
cms help
cms cc start
```

then delete workflow and initiate example, then switch between table and graph, run and see if it works

**Comment by jpfleischer** [comment]
all platforms work with 3.10.7
