### ISSUE TITLE
do the json file as pretty print

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#50]
https://cloudmesh.github.io/cloudmesh-cc/openapi.json#http://

has no spaces and new lines

use

json.dumps(data, indent=2)

or

python -m json.tool openapi.json

**Comment by jpfleischer** [comment]
https://github.com/cloudmesh/cloudmesh-cc/commit/390605c92218490243b6358889a9f479f2a43c47

make openapi has been fixed
