### ISSUE TITLE
workflow state not communicated into table

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#52]
- [x] When you run a workflow with graph view and then switch to table view the status is not communicated
- [x] Table preferences should have columns for the various timers

**Comment by jpfleischer** [comment]
a note: this only occurs when the view is switched after a workflow has completed.

**Comment by laszewsk** [comment]
i think behavieor should be that the last state is taken into account, e.g. once the workflow completed all the nodes should show up in completed state either in graph or table, only when we reset the status is eliminated or if we press run again

**Comment by jpfleischer** [comment]
please test by pulling and then going into the web server
you can try toggling columns. we have Start and End now
and the preferences page is updated
