### ISSUE TITLE
edit button does not work

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#53]

**Comment by jpfleischer** [comment]
does emacs never appear? (can you confirm that emacs is installed?) maybe mac only issue

**Comment by laszewsk** [comment]
likely emacs. best woudl if we have in cloudmesh common some way of doing this 

we should have check program cms cc check that tests if
graphviz is available
emacs is available (aquamacs default)

**Comment by jpfleischer** [comment]
please do the following, since we now have Shell.edit

```bash
cd ~/cm/cloudmesh-common
git pull
cd ~/cm/cloudmesh-cc
git pull
cms cc start --reload
```

then try the edit button on the web interface
https://github.com/cloudmesh/cloudmesh-common/blob/bf28812c2eed57e71aef3ff4cf9dd3f8fd916381/cloudmesh/common/Shell.py#L1465
